name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps & build
        run: |
          npm ci
          npm run build   # -> dist/

      - name: Deploy to Cloudflare Pages (Wrangler)
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Use your actual Pages project name below:
          command: pages deploy dist --project-name=my-porto --branch=${{ github.ref_name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Print deployment URLs
        run: |
          echo "Deployment: ${{ steps.deploy.outputs.deployment-url }}"
          echo "Alias: ${{ steps.deploy.outputs.pages-deployment-alias-url }}"
